export const METRICS_UPDATE_INTERVAL = 1000;
export const TICK_PROCESS_INTERVAL = 5000;

export const TICKS_PER_ROTATION = 16;
export const INCHES_PER_MILE = 63360;
export const SECONDS_PER_HOUR = 3600;
export const MS_PER_SECOND = 1000;

export const WHEEL_DIAMETER_INCHES = 43;
export const WHEEL_CIRCUMFERENCE_INCHES = Math.PI * WHEEL_DIAMETER_INCHES;
export const ROLLERBLADE_DIAMETER_INCHES = 3;
export const ROLLERBLADE_CIRCUMFERENCE_INCHES =
  Math.PI * ROLLERBLADE_DIAMETER_INCHES;
