export const METRICS_UPDATE_INTERVAL = 1000;
export const TICKS_PER_ROTATION = 16;
export const HALF_ROTATION = TICKS_PER_ROTATION / 2;
export const WHEEL_DIAMETER_INCHES = 43;
export const CIRCUMFERENCE_INCHES = Math.PI * WHEEL_DIAMETER_INCHES;
export const INCHES_PER_MILE = 63360;
export const SECONDS_PER_HOUR = 3600;
