export const METRICS_UPDATE_INTERVAL = 1000;
export const TICK_PROCESS_INTERVAL = 2000;

export const TICK_COLLECTION_SIZE = 3;

export const TICKS_PER_ROTATION = 16;
export const INCHES_PER_MILE = 63360;
export const SECONDS_PER_HOUR = 3600;
export const MS_PER_SECOND = 1000;

export const GEAR_RATIO = 15.5;
export const CAT_WHEEL_DIAMETER_INCHES = 43;
export const CAT_WHEEL_CIRCUMFERENCE_INCHES = Math.PI * CAT_WHEEL_DIAMETER_INCHES;
